# Generated by Django 4.0.1 on 2023-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_meetup_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
